apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["food-system/food-system"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2024-07-30T11:46:02Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4791fa0a-2161-4b48-be1b-1bba4c7f320c"}: {}
        f:spec:
          f:allocateLoadBalancerNodePorts: {}
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: '2024-07-31T00:39:40Z'
  name: food-system-loadbalancer
  namespace: food-system
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: food-system
      uid: 4791fa0a-2161-4b48-be1b-1bba4c7f320c
  resourceVersion: '150977'
  uid: f7d88256-107f-4ace-adce-beb82deeb739
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.26.87
  clusterIPs:
    - 10.43.26.87
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: food-system
      nodePort: 32722
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-food-system-food-system
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
