apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["food-system/food-system-db"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2024-07-30T04:12:51Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"ece0c350-3d8a-42ce-9306-11738e749c42"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":5432,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: '2024-07-30T04:12:51Z'
  name: food-system-db
  namespace: food-system
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: food-system-db
      uid: ece0c350-3d8a-42ce-9306-11738e749c42
  resourceVersion: '83323'
  uid: 87b9881f-64a6-4df5-90b2-0c815a815d43
spec:
  clusterIP: 10.43.167.44
  clusterIPs:
    - 10.43.167.44
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: food-system
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-food-system-food-system-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
